# Generated by Django 4.2.23 on 2025-08-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('rating', models.FloatField(default=0.0)),
                ('review_count', models.IntegerField(default=0)),
                ('price_level', models.CharField(choices=[('budget', 'Budget-Friendly'), ('moderate', 'Moderate'), ('premium', 'Premium')], default='moderate', max_length=20)),
                ('vibe', models.CharField(choices=[('peaceful', 'Peaceful & Quiet'), ('social', 'Social & Lively'), ('cozy', 'Cozy & Intimate'), ('trendy', 'Trendy & Modern'), ('traditional', 'Traditional & Classic')], default='cozy', max_length=50)),
                ('atmosphere', models.CharField(choices=[('study', 'Great for Studying'), ('meeting', 'Good for Meetings'), ('date', 'Perfect for Dates'), ('family', 'Family-Friendly'), ('work', 'Work-Friendly')], default='meeting', max_length=100)),
                ('matcha_quality', models.CharField(choices=[('premium', 'Premium Grade'), ('ceremonial', 'Ceremonial Grade'), ('culinary', 'Culinary Grade'), ('standard', 'Standard Grade')], default='standard', max_length=20)),
                ('has_outdoor_seating', models.BooleanField(default=False)),
                ('has_wifi', models.BooleanField(default=True)),
                ('has_power_outlets', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Matcha Café',
                'verbose_name_plural': 'Matcha Cafés',
                'ordering': ['-rating', '-review_count'],
            },
        ),
    ]
